image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:
  - java -jar ./artifacts/app-order.jar -port=7777 &
  - chmod +x gradlew

build_script:
  - chmod +x gradlew
  - ./gradlew test -Dselenium.headless=true --info
