image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  - cmd: java -jar ./artifacts/app-order.jar -port=7777 &

build_script:
  - chmod +x gradlew
  - chmod +x chromedriver
  - ./gradlew test --info